name: Build OpenWrt GG

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - '.github/workflows/myjob.yml'

  schedule:
    - cron: 58 3 2 * *
#  watch:
#    types: [started]


env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_TARGET: x86_64
  DEFCONFIG_FILE: ./makeconfig.d/x86_64/.config
  DIY_SH: diy.sh
  FREE_UP_DISK: true
  UPLOAD_FIRMWARE: true
  UPLOAD_FIRMWARE_TRANSFER: true
  CACHE: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu:20.04

    steps:
      # 本地代码
      - name: 【User】 Checkout
        uses: actions/checkout@master
        
#       - uses: addnab/docker-run-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           registry: gcr.io
#           image: huanghuibin/ubuntu-openwrt:x86
#           run: |
#             echo "Running Script"
#             cd /data0/lede
#             ls
#             /work/run-script
            
      - uses: hujiulong/action-qiniu-upload@master
        with:
          # Your qiniu access key, required.
          access_key: ${{ secrets.QINIU_ACCESS_KEY }}

          # Your qiniu secret key, required.
          secret_key: ${{ secrets.QINIU_SECRET_KEY }}

          # Bucket name, required.
          bucket: ${{ secrets.QINIU_BUCKET }}

          # The local directory (or file) you want to upload to bucket.
          # Default: './'
          source_dir: './makeconfig.d/x86_64/.config'

          # The directory inside of the bucket you want to upload to, namely key prefix prepended to dest file key.
          # Default: '/'
          dest_dir: '/static'

          # Whether to ignore source maps.
          # Default: true
          ignore_source_map: true
