name: Build OpenWrt Test

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test.yml'

  schedule:
    - cron: 58 3 2 * *
#  watch:
#    types: [started]


env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_TARGET: x86_64
  DEFCONFIG_FILE: ./makeconfig.d/x86_64/.config
  DIY_SH: diy.sh
  FREE_UP_DISK: true
  UPLOAD_FIRMWARE: true
  UPLOAD_FIRMWARE_TRANSFER: true
  CACHE: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu:20.04

    steps:
      # 本地代码
      - name: 【User】 Checkout
        uses: actions/checkout@master
        
      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: gcr.io
          image: huanghuibin/ubuntu-openwrt:x86
          run: |
            echo "Running Script"
            cd /data0/lede
            ls
            /work/run-script
