name: test

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test.yml'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 本地代码
      
      - name: 【User】 transfer
        uses: actions/javascript-action@v1
        with:
          milliseconds: 1000
 
      # 自定义脚本
      - name: 【User】Run DIY sh
        run: |
          touch a.txt
          echo "ccccc" >> a.txt          
          
      - name: 【OpenWrt】 Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware 
          path: a.txt

      - name: 【User】 transfer
        id: transfer
        uses: biner/transfer@master
        with:
          platform: arp
          path: a.txt

      - name: Get the output time
        run:  echo "::warning ::${{ steps.transfer.outputs.uri }}"
