name: Build OpenWrt Test

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
     # - 'makeconfig.d/newifi-d2/.config'
      - '.github/workflows/test.yml'

  schedule:
    - cron: 59 3 1 * *
#  watch:
#    types: [started]

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_TARGET: test224569
  DEFCONFIG_FILE: ./makeconfig.d/newifi-d2/.config
  FREE_UP_DISK: true
  UPLOAD_FIRMWARE: true
  UPLOAD_FIRMWARE_TRANSFER: false
  CACHE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    # container:
    #   image: huanghuibin/ubuntu-openwrt
    #   credentials:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      # 本地代码
      - name: 【User】 Checkout
        uses: actions/checkout@master
      # 完整的openwrt源码
      - name: 【OpenWrt】 Clone source code
        run: |
          mkdir openwrt
          mkdir openwrt/helloworld

      - name: 【OpenWrt】 space show
        run: |
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          cd openwrt
          du -h --max-depth=1 ./ 
          echo "======================="
          if [ -d ./build_dir ]; then
              du -h --max-depth=1 ./build_dir
          fi

          echo "======================="
          if [ -d ./staging_dir ]; then
              du -h --max-depth=1 ./staging_dir
          fi




      # 下载文件
      - name: 【Cache】 openwrt dl
        id: cache-primes
        if: env.CACHE == 'true'
        uses: actions/cache@v2
        env:
          cache-name: openwrt
        with:
          path: |
            ./openwrt
            !./openwrt/build_dir/target*_musl
            !./openwrt/aaa
          key:  ${{ env.cache-name }}-${{ env.CONFIG_TARGET }}-${{ env.FIRMWARE_HASH }}
          restore-keys: |
            ${{ env.cache-name }}-${{ env.CONFIG_TARGET }}-
            ${{ env.cache-name }}-
            
      - name: 【OpenWrt】 space show
        run: |
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          cd openwrt
          du -h --max-depth=1 ./ 
          echo "======================="
          if [ -d ./build_dir ]; then
              du -h --max-depth=1 ./build_dir
          fi

          echo "======================="
          if [ -d ./staging_dir ]; then
              du -h --max-depth=1 ./staging_dir
          fi

      - name: 【OpenWrt】 format
        run: |
          echo "======================="
          echo "Space usage:"
          cd openwrt
          if [ ! -d ./aaa ]; then
              mkdir aaa
          fi
          
          echo 1111 > ./aaa/test.txt
          if [ -d ./build_dir ]; then
              mkdir build_dir/target123213_musl
          fi
