name: test

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test.yml'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_TARGET: newifi-d2
  DEFCONFIG_FILE: ./makeconfig.d/newifi-d2/.config
  DIY_SH: diy.sh
  FREE_UP_DISK: true
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: false
  CACHE: false
  CACHE_VERSION: 1
  TZ: Asia/Shanghai
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 本地代码
      - name: 【User】 Checkout
        uses: actions/checkout@master
      # 完整的openwrt源码
      - name: 【OpenWrt】 Clone source code
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt 
          echo " git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt "
          git log --oneline -1 >> /tmp/package-lock.json
          cat /tmp/package-lock.json
          echo "::set-env name=FIRMWARE_HASH::$(cat /tmp/package-lock.json | md5sum |cut -d" " -f1)"

      # 工具链
      - name: 【Cache】 openwrt tmp_dir
        uses: actions/cache@master
        env:
          cache-name: cache-openwrt-tmp-dir
        with:
          path: ./openwrt/tmp
          key: ${{ runner.os }}-${{ env.CONFIG_TARGET }}-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-${{ env.FIRMWARE_HASH }}
          restore-keys: ${{ runner.os }}-${{ env.CONFIG_TARGET }}-${{ env.cache-name }}-${{ env.CACHE_VERSION }}
        
#       # 自定义脚本
#       - name: 【User】Run DIY sh
#         run: |
#           cat ./openwrt/dl/a.txt
#           echo ${{ github.sha }} >> ./openwrt/dl/a.txt        

#       - name: 【OpenWrt】 Upload artifact
#         uses: actions/upload-artifact@master
#         with:
#           name: OpenWrt firmware 
#           path: a.txt

#       - name: 【User】 transfer
#         id: transfer
#         uses: biner/transfer@master
#         with:
#           platform: arp
#           path: a.txt

#       - name: Get the output time
#         run:  echo "::warning ::${{ steps.transfer.outputs.uri }}"
