name: test

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test.yml'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 本地代码
      
      
      # 自定义脚本
      - name: 【User】Run DIY sh
        run: |
          mkdir a.txt
          
          
      - name: 【User】 transfer
        uses: biner/transfer@master
        with:
          platform: arp
          path: a.txt
