name: Build OpenWrt Test

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
     # - 'makeconfig.d/newifi-d2/.config'
      - '.github/workflows/test.yml'

  schedule:
    - cron: 59 3 1 * *
#  watch:
#    types: [started]

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_TARGET: test
  DEFCONFIG_FILE: ./makeconfig.d/newifi-d2/.config
  FREE_UP_DISK: true
  UPLOAD_FIRMWARE: true
  UPLOAD_FIRMWARE_TRANSFER: false
  CACHE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    # container:
    #   image: huanghuibin/ubuntu-openwrt
    #   credentials:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      # 本地代码
      - name: 【User】 Checkout
        uses: actions/checkout@master
      # 完整的openwrt源码
      - name: 【OpenWrt】 Clone source code
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
          cd openwrt
          git log  -1 --format='%H'
          echo "FIRMWARE_HASH=$(git log  -1 --format='%H')" >> $GITHUB_ENV



      # 下载文件
      - name: 【Cache】 openwrt dl
        id: cache-primes
        if: env.CACHE == 'true'
        uses: actions/cache@v2
        env:
          cache-name: cache-openwrt
        with:
          path: |
            ./openwrt
            !./openwrt/build_dir/target*_musl/
            !./openwrt/bin/
            !./openwrt/mytest/
          key:  ${{ env.cache-name }}-${{ env.CONFIG_TARGET }}-${{ env.FIRMWARE_HASH }}

      - name: 【OpenWrt】 space show
        run: |
          cd openwrt
          du -h --max-depth=1 ./ 


      - name: 【OpenWrt】 space show
        run: |
          cd openwrt
          if [ ! -d ./mytest ]; then
              mkdir mytest
          fi

          du -h --max-depth=1 ./ 
