#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build OpenWrt x86_64

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
#       - 'makeconfig.d/x86_64/.config'
      - '.github/workflows/x86_64.yml'

  schedule:
    - cron: 58 3 2 * *
#  watch:
#    types: [started]


env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_TARGET: x86_64
  DEFCONFIG_FILE: ./makeconfig.d/x86_64/.config
  DIY_SH: diy.sh
  FREE_UP_DISK: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: false
  CACHE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
#     container:
#       image: huanghuibin/ubuntu-openwrt
#       credentials:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_PASSWORD }}


#          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
#          sudo -E apt-get -qq autoremove --purge
#          sudo -E apt-get -qq clean

    steps:
      - name: 【Linux】 Free up disk space
        run: |
          sudo -E apt update -y
          sudo -E apt full-upgrade -y
          sudo -E apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      # 缓存文件
      - name: 【User】 Checkout
        uses: actions/checkout@master
      # 完整的openwrt源码
      - name: 【OpenWrt】 Clone source code
        run: |
          mkdir ~/data0
          cd ~/data0
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH lede
          git log  -1 --format='%H'
          git log --oneline -1 | md5sum |cut -d" " -f1
          echo "FIRMWARE_HASH=$(git log  -1 --format='%H')" >> $GITHUB_ENV

      # 缓存文件
      - name: 【Cache】 openwrt staging_dir
        id: cache-staging
        if: env.CACHE == 'true'
        uses: actions/cache@master
        env:
          cache-name: cache-staging
        with:
          path: |
            ~/data0/lede/staging_dir
          key:  ${{ env.cache-name }}-${{ env.CONFIG_TARGET }}-${{ env.FIRMWARE_HASH }}
          restore-keys: |
            ${{ env.cache-name }}-${{ env.CONFIG_TARGET }}-
            ${{ env.cache-name }}-
            
      # 下载文件
      - name: 【Cache】 openwrt tmp
        id: cache-bin
        if: env.CACHE == 'true'
        uses: actions/cache@master
        env:
          cache-name: cache-tmp
        with:
          path: |
            ~/data0/lede/tmp
          key:  ${{ env.cache-name }}-${{ env.CONFIG_TARGET }}-${{ env.FIRMWARE_HASH }}
          restore-keys: |
            ${{ env.cache-name }}-${{ env.CONFIG_TARGET }}-
            ${{ env.cache-name }}-


      # 下载文件
      - name: 【Cache】 openwrt build
        id: cache-primes
        if: env.CACHE == 'true'
        uses: actions/cache@master
        env:
          cache-name: cache-build
        with:
          path: |
            ~/data0/lede/build_dir
          key:  ${{ env.cache-name }}-${{ env.CONFIG_TARGET }}-${{ env.FIRMWARE_HASH }}
          restore-keys: |
            ${{ env.cache-name }}-${{ env.CONFIG_TARGET }}-
            ${{ env.cache-name }}-
            
      # 下载文件
      - name: 【Cache】 openwrt build
        id: cache-dl
        if: env.CACHE == 'true'
        uses: actions/cache@master
        env:
          cache-name: cache-dl
        with:
          path: |
            ~/data0/lede/dl
          key:  ${{ env.cache-name }}-${{ env.CONFIG_TARGET }}-${{ env.FIRMWARE_HASH }}
          restore-keys: |
            ${{ env.cache-name }}-${{ env.CONFIG_TARGET }}-
            ${{ env.cache-name }}-
            

      - name: ext package
        run: |
          cd ~/data0/lede 
          echo 'src-git helloworld https://github.com/fw876/helloworld' >>feeds.conf.default
          echo 'src-git passwall https://github.com/xiaorouji/openwrt-passwall' >>feeds.conf.default
          
          

      - name: 【OpenWrt】 Update feeds
        run: cd ~/data0/lede && ./scripts/feeds update -a

      - name: 【OpenWrt】 Install feeds
        run: cd ~/data0/lede && ./scripts/feeds install -a

      # 自定义配置
      - name: 【OpenWrt】 Load custom configuration
        run: |
          cp $DEFCONFIG_FILE ~/data0/lede/.config
          echo "defconfig start"
          cd ~/data0/lede
          make defconfig

      # openwrt 下载package    
      - name: 【OpenWrt】 Download package
        id: package
        run: |
          cd ~/data0/lede
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          
      - name: 【OpenWrt】 space show
        run: |
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          cd ~/data0/lede
          du -h --max-depth=1 ./ 
          echo "======================="
          if [ -d ./build_dir ]; then
              du -h --max-depth=1 ./build_dir
          fi
          echo "======================="
          if [ -d ./bin ]; then
              du -h --max-depth=1 ./staging_dir
          fi
          echo "======================="
          if [ -d ./bin ]; then
              du -h --max-depth=1 ./bin
          fi
          
      # openwrt 编译固件 
      - name: 【OpenWrt】 Compile the firmware
        id: compile
        run: |
          export FORCE_UNSAFE_CONFIGURE=1
          cd ~/data0/lede
          echo "======================="
          echo -e "thread compile: $(nproc) "
          make -j$(($(nproc) + 1)) || make -j1 V=s
          echo "======================="
          echo "::set-output name=status::success"
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
    
      - name: 【OpenWrt】 space show
        run: |
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          cd ~/data0/lede
          du -h --max-depth=1 ./ 
          echo "======================="
          if [ -d ./build_dir ]; then
              du -h --max-depth=1 ./build_dir
          fi
          echo "======================="
          if [ -d ./bin ]; then
              du -h --max-depth=1 ./staging_dir
          fi
          echo "======================="
          if [ -d ./bin ]; then
              du -h --max-depth=1 ./bin
          fi

      - name: Organize files
        id: organize
        if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
        run: |
          echo "FIRMWARE=~/data0/lede/bin/targets" >> $GITHUB_ENV
          echo "::set-output name=status::success"
        

      - name: 【OpenWrt】 Upload artifact
        uses: actions/upload-artifact@master
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          name: OpenWrt-${{ env.CONFIG_TARGET }} 
          path: |
            ~/data0/lede/bin/targets/
            !~/data0/lede/bin/targets/**/packages
            !~/data0/lede/bin/targets/**/*initramfs-kernel.bin

      - name: Upload firmware directory
        uses: actions/upload-artifact@master
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE }}
        
      - name: Upload firmware to cowtransfer
        id: cowtransfer
        if: steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
          echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
          echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"
          
      - name: Upload firmware to WeTransfer
        id: wetransfer
        if: steps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
          echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
          echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"


